### ISSUE TITLE
Problem last flash 

### ISSUE THREAD

**Issue by Diegocampy** [yaourdt/tasmota-to-mgos#4] opened 2021-01-11 19:27 UTC
I need help becouse I flash the tasmota minimal in my Shelly1
after i flash 0x1000 and after i try to flash Shelly firmware with: 
curl -i -F filedata=@SHSW-1.zip http://10.42.42.44/update
i receive the message "1 update applied, rebooting" but in the end even after rebooting the same wifi network mg-xxxxx reappears and not a new Shelly ... 

Now I don't understand the reason for this problem, but I have a possible hypotheses:
 I may have been wrong to flash the 0x7000 file instead of the 0x1000 (I doubt but I consider it as a hypothesis) I read: "Be careful to pick the appropriate version, or the device will be bricked during the first boot of the target firmware!" So if I can access the wifi network and it also starts up, I don't think I broke it so I feel like excluding the wrong firmware right? There is way to check which of the two firmware I have installed

Do you have any advice for me? From here can I try to flash some tasmota in case to bring it back active?

**Comment by yaourdt** [comment] 2021-01-12 07:52
This is very likely the wrong firmware version, as the Shelly 1 is tested and known to work. If you flashed the wrong firmware version, what you can try to do is use mgos-to-tasmota to convert back to tasmota, then try again with the correct image, 0x1000 for the Shelly 1. I have never tested this approach, but it could work. Please report back.

Also, please do not [hijack other people's issues](https://github.com/yaourdt/tasmota-to-mgos/issues/3#issuecomment-758280921).

**Comment by yaourdt** [comment] 2021-01-12 07:59
Just one last thought: If you decide to go back, your device will need a working network connection after flashing mgos-to-tasmota to download Tasmota. You can do that for example by using the backup WIFI with SSID `mgos-recover` and password `RJoPuKC3u5`, or by compiling mgos-to-tasmota your self with the credentials of your own Wi-Fi. See the mgos-to-tasmota readme for both options

**Comment by Diegocampy** [comment] 2021-01-12 09:54
Thank you very much for your availability and I apologize first of all for having hijack other people's issues.
now i hope i can ask here, even if the request is perhaps about mgos-to-tasmota
I'm missing a step, I don't understand how to do mgos-to-tasmota. Now I find myself with the device visible on the network with its wifi, but accessible only from the windows dos prompt. I tried the curl commands as written before, which just doesn't work.
I don't understand which is the way to go. 
I can not use the command use in the past to flash my shelly1 to tasmota (http://shellyip/ota?url=http://dl.dasker.eu/firmware/mg2tasmota-Shelly1.zip) becouse My shelly now is mgos and this is not connect to my wifi, but it has its own wifi network which I can connect to but obviously without internet access. 
I have read the readme, but my lack of domesticity does not make me understand how to proceed

**Comment by yaourdt** [comment] 2021-01-12 10:31
For the suggested path, you need to go back to Tasmota, before you can go forward again. To do so, flash mgos-to-tasmota using curl instead of the Shelly firmware. Pick a version with matching boot configuration, using the wrong configuration could lead to problems. If you really flashed 0x7000 instead of 0x1000, use for example the Shelly Plug S version of mgos-to-tasmota, as it boots from 0x7000.

Once you have flashed mgos-to-tasmota using curl, the intermediate firmware will need internet access to download Tasmota. As you are not coming from a fully configured version of Mongoose OS, the firmware will most likely be missing your Wi-Fi credentials. In this case, create a new Wi-Fi (use for example your routers guest network) with the backup credentials stated in my comment above. If all goes well, the device will connect to the Wi-Fi, convert to Tasmota, and you can try again.

Let me stress this again: This is not a trivial operation, it is untested, and may fail. If you get stuck along the way, the best way I can help you is if you provide as much information as possible.

**Comment by Diegocampy** [comment] 2021-01-12 11:00
sorry, I still do not understand and I ask you to be patient, I have always made do with trying, but I am not a programmer and I have never studied anything like this, just lots of tests for anything
Anyway, when you write "flash mgos-to-tasmota using curl" you mean with this string
curl -i -F filedata=@c:\shblb-1.zip http://10.42.42.44/update but changing instead of c: \ shblb-1.zip with a different zip file? 
I don't know if I used 0x7000 instead of 0x1000 it's just my guess seeing that the reset and new flash didn't work (start of my described problem, I just hang there)
So let's assume that I used the 7x1000, which zip file should I use? Download this http://dl.dasker.eu/firmware/mg2tasmota-ShellyPlugS.zip move in c:\ and:
curl -i -F filedata=@c:\ShellyPlugS.zip http://10.42.42.44/update ???
I'm not sure I understand

**Comment by yaourdt** [comment] 2021-01-12 12:12
No worries, we can try to move forward step by step. Without attaching a serial console, there is unfortunately no way to tell which version of tasmota-to-mgos is running.

But let's take a step back: Can you please confirm you are using the right Shelly firmware for the right device? You say you have a Shelly 1, but use `c:\shblb-1.zip` in your example. A Shelly 1 would require `SHSW-1.zip`

**Comment by Diegocampy** [comment] 2021-01-12 12:59
Yes I use SHSW-1.zip (now i correct the first post, I mistake with copy and past. My first device I tried was the bulb and I was able to recover it and go back to the original Shelly firmware. Now I try with a Shelly1. That's why I was wrong to paste the address.
I must say that when I am stuck with mgos I then tried many different firmware but always shelly1

**Comment by Diegocampy** [comment] 2021-01-12 21:54
I try it:

C:\>curl -i -F filedata=@c:\mg2tasmota-ShellyPlugS.zip http://10.42.42.44/update
HTTP/1.1 200 OK
Server: Mongoose/6.18
Content-Type: text/plain
Connection: close

1 Update applied, rebooting

and now i don't see new wifi... i think this is definitely dead :-( 
probably the flashed firmware was correctly 0x1000 and now with this attempt I have burned it.
Not seeing it online, I can't do any more tests, I can only remove it. Thanks anyway for trying to help me

**Comment by yaourdt** [comment] 2021-01-13 10:26
Or you are now at this point:

> Once you have flashed mgos-to-tasmota using curl, the intermediate firmware will need internet access to download Tasmota. As you are not coming from a fully configured version of Mongoose OS, the firmware will most likely be missing your Wi-Fi credentials. In this case, create a new Wi-Fi (use for example your routers guest network) with the backup credentials stated in my comment above. If all goes well, the device will connect to the Wi-Fi, convert to Tasmota, and you can try again.

**Comment by Diegocampy** [comment] 2021-01-13 11:15
Ok, yesterday I thought it might be like this, I entered those credentials in my guest router but then I didn't see any new devices connected to it appear, so I had restored it to the original name. Now that you tell me so, I try again and leave it on, if everything works fine, I expect to see then doing a wifi scan, a new network called tasmota right? I'll let you know, thanks

**Comment by yaourdt** [comment] 2021-01-14 09:55
If you are still stuck I think we have a new bug; I'll try to reproduce it. You can still recover your device by attaching a programmer, I can however not support you with that.

**Comment by yaourdt** [comment] 2021-01-14 10:14
I cannot reproduce this bug. If anyone experiences the same problem, please attach a log similar to this.
```
[Jan 14 11:11:29.861] mgos_http_server.c:180  0x3fff1c3c HTTP connection from 10.42.42.50:55096
[Jan 14 11:11:30.873] mgos_ota_core.c:252     Starting, timeout 600, commit timeout 0, mem 40736
[Jan 14 11:11:30.883] mgos_mongoose.c:66      New heap free LWM: 37104
[Jan 14 11:11:30.887] mgos_mongoose.c:66      New heap free LWM: 36976
[Jan 14 11:11:30.895] mgos_mongoose.c:66      New heap free LWM: 36384
[Jan 14 11:11:30.903] mgos_ota_core.c:486     FW: switch1 esp8266 1.0 20201228-092119/v1.9.3@ad2bb4e3
[Jan 14 11:11:30.913] esp_ota_backend.c:185   Slot 1, FW: switch1.bin -> 0x108000, FS fs.bin -> 0x1bb000
[Jan 14 11:11:30.926] mgos_mongoose.c:66      New heap free LWM: 35888
[Jan 14 11:11:30.930] mgos_ota_core.c:504     0.18% total, esp_init_data_default_v08.bin 128 of 128
[Jan 14 11:11:31.043] esp_ota_backend.c:338   Start writing fs.bin (262144) @ 0x1bb000
[Jan 14 11:11:31.081] mgos_ota_core.c:504     0.24% total, fs.bin 512 of 262144
[Jan 14 11:11:31.091] mgos_mongoose.c:66      New heap free LWM: 35624
[Jan 14 11:11:32.543] mgos_mongoose.c:66      New heap free LWM: 35608
[Jan 14 11:11:32.550] mgos_mongoose.c:66      New heap free LWM: 35528
[Jan 14 11:11:34.135] esp_ota_backend.c:376   Write finished, checksum ok
[Jan 14 11:11:34.145] mgos_ota_core.c:504     31.18% total, rboot.bin 512 of 2320
[Jan 14 11:11:34.384] esp_ota_backend.c:338   Start writing switch1.bin (580688) @ 0x108000
[Jan 14 11:11:34.393] mgos_mongoose.c:66      New heap free LWM: 35488
[Jan 14 11:11:34.429] mgos_ota_core.c:504     31.46% total, switch1.bin 512 of 580688
[Jan 14 11:11:34.693] mgos_mongoose.c:66      New heap free LWM: 35392
[Jan 14 11:11:37.440] mgos_ota_core.c:504     62.40% total, switch1.bin 262656 of 580688
[Jan 14 11:11:40.251] mgos_ota_core.c:504     93.34% total, switch1.bin 524800 of 580688
[Jan 14 11:11:41.254] esp_ota_backend.c:376   Write finished, checksum ok
[Jan 14 11:11:41.257] mgos_ota_core.c:630     Reached the end of archive
[Jan 14 11:11:41.262] esp_ota_backend.c:410   Resetting RF calibration data @ 0x1fb000
[Jan 14 11:11:41.326] esp_ota_backend.c:442   New rboot config: prev_rom: 0, current_rom: 1 current_rom addr: 0x108000, current_rom size: 580688, current_fs addr: 0x1bb000, current_fs size: 262144
[Jan 14 11:11:41.340] mgos_ota_core.c:811     Update finished, result 1 (Update applied, rebooting)
[Jan 14 11:11:41.348] mgos_ota_core.c:853     Update requires reboot
[Jan 14 11:11:41.353] mgos_system.c:58        Rebooting in 500 ms
[Jan 14 11:11:41.858] mgos_vfs.c:1026         Unmounting filesystems
[Jan 14 11:11:41.862] esp_main.c:158          SDK: station: 14:7d:da:a9:91:4d leave, AID = 1
[Jan 14 11:11:41.868] esp_main.c:158          SDK: rm 1
[Jan 14 11:11:41.871] esp_main.c:158          SDK: bcn 0
[Jan 14 11:11:41.874] esp_main.c:158          SDK: del if1
[Jan 14 11:11:41.880] esp_main.c:158          SDK: del if0
[Jan 14 11:11:41.883] esp_main.c:158          SDK: usl
[Jan 14 11:11:41.886] esp_main.c:158          SDK: mode : null
[Jan 14 11:11:41.889] mgos_system.c:43        Restarting
[Jan 14 11:11:41.892] 
[Jan 14 11:11:41.892]  ets Jan  8 2013,rst cause:2, boot mode:(3,7)
[Jan 14 11:11:41.897] 
[Jan 14 11:11:41.897] load 0x40100000, len 1724, room 16 
[Jan 14 11:11:41.901] tail 12
[Jan 14 11:11:41.901] chksum 0x17
[Jan 14 11:11:41.904] ho 0 tail 12 room 4
[Jan 14 11:11:41.904] load 0x3ffe8000, len 832, room 12 
[Jan 14 11:11:41.907] tail 4
[Jan 14 11:11:41.910] chksum 0xe2
[Jan 14 11:11:41.910] csum 0xe2
[Jan 14 11:11:41.910] rBoot v1.2.1-cesanta1-yaourdt - richardaburton@gmail.com
[Jan 14 11:11:41.915] Flash Size:   32 Mbit
[Jan 14 11:11:41.918] Flash Mode:   DOUT
[Jan 14 11:11:41.918] Flash Speed:  80 MHz
[Jan 14 11:11:41.921] rBoot Option: Big flash
[Jan 14 11:11:41.924] rBoot Option: move esp init data
[Jan 14 11:11:41.928] 
[Jan 14 11:11:41.928] Moving SDK config sectors before booting.
[Jan 14 11:11:42.071] First boot, attempt 0
[Jan 14 11:11:42.071] Boot is unconfirmed
[Jan 14 11:11:42.135] Booting rom 1 (0x108000).
[Jan 14 11:11:42.157]  ...mode : softAP(86:f3:eb:5a:17:f
[Jan 14 11:11:42.647] bcn 0
[Jan 14 11:11:42.647] del if1
[Jan 14 11:11:42.647] usl
[Jan 14 11:11:42.647] mode : null
[Jan 14 11:11:42.647] mode : softAP(86:f3:eb:5a:17:ff)
[Jan 14 11:11:42.649] add if1
[Jan 14 11:11:42.652] dhcp server start:(ip:192.168.4.1,mask:255.255.255.0,gw:192.168.4.1)
[Jan 14 11:11:42.658] bcn 100
[Jan 14 11:11:42.658] bcn 0
[Jan 14 11:11:42.658] del if1
[Jan 14 11:11:42.660] usl
[Jan 14 11:11:42.660] add if1
[Jan 14 11:11:42.660] dhcp server start:(ip:192.168.4.1,mask:255.255.255.0,gw:192.168.4.1)
[Jan 14 11:11:42.667] bcn 100
[Jan 14 11:11:42.789] bcn 0
[Jan 14 11:11:42.789] del if1
[Jan 14 11:11:42.789] usl
[Jan 14 11:11:42.789] mode : null
[Jan 14 11:11:42.789] 
[Jan 14 11:11:42.789] 
[Jan 14 11:11:42.792] SHSW-1-5A17FF 84:F3:EB:5A:17:FF
[Jan 14 11:11:42.794] 
[Jan 14 11:11:42.891] 
[Jan 14 11:11:42.892]  ets Jan  8 2013,rst cause:2, boot mode:(3,7)
```

**Comment by Diegocampy** [comment] 2021-01-14 11:12
> If you are still stuck I think we have a new bug; I'll try to reproduce it. You can still recover your device by attaching a programmer, I can however not support you with that.

Don't worry, I thank you for the support given, I just have to take it off and keep it aside. Maybe one day I'll want to try to restore it, for now no, I don't have the equipment to do it. I plan to switch to zigbee or z-wave devices as I need to replace my devices.
For me the question is closed, but I did not understand if I have to close the issue with the button below, or if I have to leave it open for any other users to add the info you requested

**Comment by yaourdt** [comment] 2021-01-14 12:49
Ok, let's keep it open for a while then, maybe I'll get around to understanding the problem at one point

**Comment by yaourdt** [comment] 2021-02-02 07:45
Fixed with latest release

**Closed by yaourdt** 2021-02-02 07:45 UTC
