### ISSUE TITLE
-12 Write failed on Shelly RGB2

### ISSUE THREAD

**Issue by Diegocampy** [yaourdt/tasmota-to-mgos#5] opened 2021-01-18 22:03 UTC
I'm back! After failing with a Shelly1 and then being able to flash other Shellys, I got stuck while flashing a shelly rgbw2

The operations carried out are:
1) flashed the minimal firmware tasmota ota mode http://ota.tasmota.com/tasmota/release/tasmota-minimal.bin
Completed successfully

2) flashed 0x7000 firmware https://github.com/yaourdt/tasmota-to-mgos/raw/main/binaries/mgos512k-0x7.bin
Completed successfully
3) connected to the mg wifi network - ????? and once connected:ù in prompt i type:

C:\>curl -i -F filedata=@c:\SHRGBW2.zip http://10.42.42.44/update
HTTP/1.1 500 Internal Server Error
Server: Mongoose/6.18
Content-Type: text/plain
Connection: close

-12 Write failed

curl: (56) Recv failure: Connection was aborted

I am stuck here ... rgb2w.zip file is correct i am sure
If you have any suggestions for me, thank you

**Comment by yaourdt** [comment] 2021-01-21 12:31
This is similar to #3 - none of the users there has provided me with logs, however, and I cannot reproduce the bug. If you can provide me with logs, that would be much appreciated. If not, please be patient, I'm trying to narrow down the issue

**Comment by Diegocampy** [comment] 2021-01-21 14:12
But imagine, don't worry, you're using your time to help people for free, I have nothing to blame you for. Unfortunately I'm not able to do any debugging, I don't know how to do it. I chose to try to convert the shelly with this guide precisely because it is done via OTA without having to connect anything, because I do not have the tools, and I would not be able

**Comment by yaourdt** [comment] 2021-02-01 12:24
I'll just close this issue, as it the same as #3, we can continue discussion there

**Closed by yaourdt** 2021-02-01 12:24 UTC
